version: '3.1'

services:

  perseo:
    build: .
    ports:
      - 13080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
      - adminer

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=perseo
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 13081:8080
    links:
      - mysql

  composer:
    image: composer
    user: 1000:1000
    volumes: ['.:/app']

volumes:
  mysql:
